sudo: true
language: haskell

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:

  - ghc: 9.0.1
  - ghc: 8.10.7
  - ghc: 8.8.4

install:
  - |
    ghc --version
    cabal --version
    cabal new-update
    cabal new-build --enable-tests --enable-benchmarks

script:
  - |
    cabal new-test --enable-tests
